[platformio]
default_envs = cyd_2432s028

[env:cyd_2432s028]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions.csv
lib_deps =
  bodmer/TFT_eSPI @ ^2.5.43
  tzapu/WiFiManager @ ^2.0.17
  bblanchon/ArduinoJson @ ^7.2.1
  h2zero/NimBLE-Arduino @ ^2.2.0
build_flags =
  -D USER_SETUP_LOADED
  ; TPM408-2.8 panels on this CYD use the standard ILI9341 command set.
  -D ILI9341_DRIVER
  -D TFT_WIDTH=240
  -D TFT_HEIGHT=320
  -D TFT_MISO=12
  -D TFT_MOSI=13
  -D TFT_SCLK=14
  -D TFT_CS=15
  -D TFT_DC=2
  -D TFT_RST=-1
  -D TFT_BL=21
  -D TFT_BACKLIGHT_ON=HIGH
  -D TOUCH_CS=33
  -D SPI_FREQUENCY=40000000
  -D SPI_TOUCH_FREQUENCY=2500000
  -D USE_HSPI_PORT
  -D CORE_DEBUG_LEVEL=0
